# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
admin = UserType.create name: 'admin', long_name: 'Administrador'
chief_lawyer = UserType.create name: 'chief_lawyer', long_name: 'Abogado Jefe'
assistant = UserType.create name: 'assistant', long_name: 'Asistente'

#Profiles
#puts 'LOL!'
all = Subject.create name: 'Todo', class_name: ':all'
causas = Subject.create name: 'Causas', class_name: 'Cause'
avances = Subject.create name: 'Avances', class_name: 'JournalEntry'
pagos = Subject.create name: 'Pagos', class_name: 'Payment'

manage = Action.create long_name: 'Administrar', name: 'manage'

manage_all = Permission.create subject: all, action: manage
manage_causes = Permission.create subject: causas, action: manage
manage_je = Permission.create subject: avances, action: manage
manage_payments = Permission.create subject: pagos, action: manage

sudo_profile = Profile.create long_name: 'Super Administrador', name: 'sudo', permissions: [manage_all]
organization_admin_profile = Profile.create long_name: 'Administrador', name: 'admin', permissions: [manage_causes, manage_je, manage_payments]
lawyer_profile = Profile.create long_name: 'Abogado', name: 'lawyer', permissions: [manage_causes, manage_je]
executive_profile = Profile.create long_name: 'Ejecutivo', name: 'executive', permissions: [manage_payments]


Setting.create [{long_name: 'Cantidad de Casos', name: 'cases_quantity'},
	{long_name: 'Cantidad de Clientes', name: 'clients_quantity'},
	{long_name: 'Cantidad Causas Civiles', name: 'civil_cases_quantity'},
	{long_name: 'cantidad de causas laboral', name: 'laboral_cases_quantity'},
	{long_name: 'cantidad de causas Cobranza', name: 'cobranza_cases_quantity'},
	{long_name: 'cantidad de causas Familia', name: 'familia_cases_quantity'},
	{long_name: 'cantidad de causas Penal', name: 'penal_cases_quantity'},
	{long_name: 'cantidad de causas General', name: 'General_cases_quantity'}]

test_org = Organization.create name: 'Test Company', id_number: '111', profiles: [organization_admin_profile, lawyer_profile, executive_profile]
admin_org = Organization.create name: 'Admin', id_number: '1234', profiles: [sudo_profile]

sudo_op = OrganizationProfile.find_by_organization_id_and_profile_id admin_org.id, sudo_profile
admin_op = OrganizationProfile.find_by_organization_id_and_profile_id test_org.id, organization_admin_profile.id
lawyer_op = OrganizationProfile.find_by_organization_id_and_profile_id test_org.id, lawyer_profile.id
executive_op = OrganizationProfile.find_by_organization_id_and_profile_id test_org.id, executive_profile.id

#Admins
claudio = User.create name: 'Claudio Guerra', user_type: admin, id_number: '1', email: 'claudevandort@gmail.com', password: '12345678', password_confirmation: '12345678', organization_profile: sudo_op
pato = User.create name: 'Patricio Jara', user_type: admin, id_number: '2', email: 'patricioalfredo18@gmail.com', password: 'qwe12qwe', password_confirmation: 'qwe12qwe', organization_profile: sudo_op

test_lawyer = User.create name: 'Juan Perez', user_type: chief_lawyer, id_number: '3', email: 'juan@perez.com', password: 'juanperez', password_confirmation: 'juanperez', organization_profile: admin_op
test_assistant = User.create name: 'Nicolás Vera', user_type: assistant, id_number: '4', email: 'nico@vera.com', password: 'nicovera', password_confirmation: 'nicovera', organization_profile: lawyer_op
test_org.update users: [test_lawyer, test_assistant]
admin_org.update users: [claudio, pato]

#static stuff
#juridica = CauseType.create name: 'Causa Jurídica'
#no_judicial = CauseType.create name: 'Gestión no Judicial'
CauseState.create [{name: 'Ingreso'}, {name: 'Discución', color: 'info'}, {name: 'Prueba', color: 'success'}, {name: 'Sentencia', color: 'danger'}, {name: 'Apelación', color: 'warning'}, {name: 'Archivada', color: 'default'}]
cliente_persona = ClientType.create name: 'Persona'
cliente_empresa = ClientType.create name: 'Empresa'
PaymentState.create [{name: 'Cobrado', color: 'success'}, 
					{name: 'Por cobrar', color: ''}, 
					{name: 'Cobrar hoy', color: 'warning'}, 
					{name: 'Atrasado', color: 'danger'}]
santiago = Region.create name: 'Santiago'
san_miguel = Region.create name: 'San Miguel'
civil = Area.create name: 'Civil'
laboral = Area.create name: 'Laboral'
cobranza = Area.create name: 'Cobranza'
familia = Area.create name: 'Familia'
penal = Area.create name: 'Penal'
general = Area.create name: 'General'
supr_apel = Area.create name: 'Corte Suprema/Apelaciones'
Court.create [	{name: 'Corte Suprema', area: supr_apel, region: santiago},
				{name: 'Corte de Apelaciones de Santiago', area: supr_apel, region: santiago},
				{name: 'Corte de Apelaciones de San Miguel', area: supr_apel, region: santiago},
				{name: '1º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '2º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '3º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '4º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '5º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '6º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '7º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '8º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '9º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '10º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '11º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '12º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '13º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '14º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '15º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '16º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '17º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '18º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '19º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '20º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '21º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '22º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '23º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '24º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '25º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '26º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '27º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '28º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '29º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: '30º Juzgado Civil de Santiago', area: civil, region: santiago},
				{name: 'Juzgado de Cobranza Laboral y Previsional de Santiago', area: cobranza, region: santiago},
				{name: '1º Juzgado de Familia Santiago', area: familia, region: santiago},
				{name: '2º Juzgado de Familia Santiago', area: familia, region: santiago},
				{name: '3º Juzgado de Familia Santiago', area: familia, region: santiago},
				{name: '4º Juzgado de Familia Santiago', area: familia, region: santiago},
				{name: 'Juzgado de Familia Colina', area: familia, region: santiago},
				{name: 'Juzgado de Familia Pudahuel', area: familia, region: santiago},
				{name: 'Centro de Control de Familia', area: familia, region: santiago},
				{name: '1º Juzgado de Garantía de Santiago', area: penal, region: santiago},
				{name: '2º Juzgado de Garantía de Santiago', area: penal, region: santiago},
				{name: '3º Juzgado de Garantía de Santiago', area: penal, region: santiago},
				{name: '4º Juzgado de Garantía de Santiago', area: penal, region: santiago},
				{name: '5º Juzgado de Garantía de Santiago', area: penal, region: santiago},
				{name: '6º Juzgado de Garantía de Santiago', area: penal, region: santiago},
				{name: '7º Juzgado de Garantía de Santiago', area: penal, region: santiago},
				{name: '8º Juzgado de Garantía de Santiago', area: penal, region: santiago},
				{name: '9º Juzgado de Garantía de Santiago', area: penal, region: santiago},
				{name: '13º Juzgado de Garantía de Santiago', area: penal, region: santiago},
				{name: '14º Juzgado de Garantía de Santiago', area: penal, region: santiago},
				{name: 'Juzgado de Garantía de Colina', area: penal, region: santiago},
				{name: '1º Tribunal de Juicio Oral en lo Penal de Santiago', area: penal, region: santiago},
				{name: '2º Tribunal de Juicio Oral en lo Penal de Santiago', area: penal, region: santiago},
				{name: '3º Tribunal de Juicio Oral en lo Penal de Santiago', area: penal, region: santiago},
				{name: '4º Tribunal de Juicio Oral en lo Penal de Santiago', area: penal, region: santiago},
				{name: '5º Tribunal de Juicio Oral en lo Penal de Santiago', area: penal, region: santiago},
				{name: '7º Tribunal de Juicio Oral en lo Penal de Santiago', area: penal, region: santiago},
				{name: 'Tribunal de Juicio Oral en lo Penal Colina', area: penal, region: santiago},
				{name: '1º Juzgado de Letras del Trabajo de Santiago', area: laboral, region: santiago},
				{name: '2º Juzgado de Letras del Trabajo de Santiago', area: laboral, region: santiago},
				{name: '2º Juzgado de Letras del Trabajo de Santiago', area: laboral, region: santiago},
				{name: 'Juzgado de Letras de Colina', area: laboral, region: santiago},

				# Tribunales civiles de todo el pais

				{name: '1º Juzgado de Letras de Arica', area: civil},
				{name: '2º Juzgado de Letras de Arica', area: civil},
				{name: '3º Juzgado de Letras de Arica', area: civil},
				{name: '3º Juzgado de Letras de Arica Ex 4º', area: civil},
				{name: '1º Juzgado De Letras de Arica ex 4°', area: civil},
				{name: '2º Juzgado De Letras de Arica ex 4°', area: civil},
				{name: 'Juzgado de Letras y Gar. Pozo Almonte', area: civil},
				{name: '1º Juzgado de Letras de Iquique', area: civil},
				{name: '2º Juzgado de Letras de Iquique', area: civil},
				{name: '3º Juzgado de Letras de Iquique', area: civil}, #OKKKKKKKK

				{name: 'Juzgado de Letras Tocopilla', area: civil},
				{name: 'Juzgado de Letras y Gar.de Maria Elena', area: civil},
				{name: '1º Juzgado de Letras de Calama', area: civil},   #OKKKKKKKK

				{name: '2º Juzgado de Letras de Calama', area: civil},
				{name: 'Juzgado de Letras y Gar. de Taltal', area: civil},
				{name: '3º Juzgado de Letras de Calama', area: civil},
				{name: '1º Juzgado de Letras Civil de Antofagasta', area: civil}, #okkkk

				{name: '2º Juzgado de Letras Civil de Antofagasta', area: civil},
				{name: '3º Juzgado de Letras Civil de Antofagasta', area: civil},
				{name: '4º Juzgado de Letras Civil de Antofagasta', area: civil},
				{name: 'Juzgado de Letras y Gar. de Chañaral', area: civil}, #okkkkk

				{name: 'Juzgado de Letras de Diego de Almagro', area: civil},
				{name: '1º Juzgado de Letras de Copiapó', area: civil},
				{name: '2º Juzgado de Letras de Copiapó', area: civil}, 
				{name: '3º Juzgado de Letras de Copiapó', area: civil},
				{name: 'Juzgado de Letras y Gar.de Freirina', area: civil},
				{name: '1º Juzgado de Letras de Vallenar', area: civil},
				{name: '2º Juzgado de Letras de Vallenar', area: civil},
				{name: 'Juzgado de Letras y Gar.de Caldera', area: civil},
				{name: '4º Juzgado de Letras de Copiapó', area: civil},
				{name: '1º Juzgado de Letras de la Serena', area: civil},
				{name: '2º Juzgado de Letras de la Serena', area: civil},
				{name: '3º Juzgado de Letras de la Serena', area: civil},
				{name: '1º Juzgado de Letras de Coquimbo', area: civil},
				{name: '2º Juzgado de Letras de Coquimbo', area: civil},
				{name: '3º Juzgado de Letras de Coquimbo', area: civil},
				{name: 'Juzgado de Letras de Vicuña', area: civil},
				{name: 'Juzgado de letras y garantia de Andacollo', area: civil},
				{name: '1º Juzgado de Letras de Ovalle', area: civil},
				{name: '2º Juzgado de Letras de Ovalle', area: civil},
				{name: '3º Juzgado de Letras de Ovalle', area: civil},
				{name: 'Juzgado de Letras y Gar.de Combarbalá', area: civil},
				{name: 'Juzgado de Letras de Illapel', area: civil},
				{name: 'Juzgado de Letras y Gar. de los Vilos', area: civil},
				{name: '1º Juzgado Civil de Valparaiso', area: civil},
				{name: '2º Juzgado Civil de Valparaiso', area: civil},
				{name: '3º Juzgado Civil de Valparaiso', area: civil},
				{name: '4º Juzgado Civil de Valparaiso', area: civil},
				{name: '5º Juzgado Civil de Valparaiso', area: civil},
				{name: '1º Juzgado Civil de Viña del Mar', area: civil},
				{name: '2º Juzgado Civil de Viña del Mar', area: civil},
				{name: '3º Juzgado Civil de Viña del Mar', area: civil},
				{name: '1º Juzgado de Letras de Quilpue', area: civil},
				{name: '2º Juzgado de Letras de Quilpue', area: civil},
				{name: 'Juzgado de Letras de Villa Alemana', area: civil},
				{name: 'Juzgado de Letras de Casablanca', area: civil},
				{name: 'Juzgado de Letras de La Ligua', area: civil},
				{name: 'Juzgado de Letras y Gar. de Petorca', area: civil},
				{name: '1º Juzgado de Letras de Los Andes', area: civil},
				{name: '2º Juzgado de Letras de Los Andes', area: civil},
				{name: '1º Juzgado de Letras de San Felipe', area: civil},
				{name: '1º Juzgado de Letras de San Felipe Ex 2º', area: civil},
				{name: 'Juzgado de Letras y Gar.de Putaendo', area: civil},
				{name: '1º Juzgado de Letras de Quillota', area: civil},
				{name: '2º Juzgado de Letras de Quillota', area: civil},
				{name: 'Juzgado de Letras de La Calera', area: civil},
				{name: 'Juzgado de Letras de Limache', area: civil},
				{name: '1º Juzgado de Letras de San Antonio', area: civil},
				{name: '2º Juzgado de Letras de San Antonio', area: civil},
				{name: 'Juzgado de Letras y Gar. de Isla de Pascua', area: civil},
				{name: 'Juzgado de Letras y Gar.de Quintero', area: civil},
				{name: '1º Juzgado Civil de Rancagua', area: civil},
				{name: '2º Juzgado Civil de Rancagua', area: civil},
				{name: '1º Juzgado de Letras de Rengo', area: civil},
				{name: 'Juzgado de Letras de San Vicente de Tagua Tagua', area: civil},
				{name: '1º Juzgado de Letras y Gar.de Peumo', area: civil},
				{name: '1º Juzgado de Letras de San Fernando', area: civil},
				{name: '2º Juzgado de Letras de San Fernando', area: civil},
				{name: '1º Juzgado de Letras de Santa Cruz', area: civil},
				{name: '1º Juzgado De Letras De Santa Cruz Ex 2°', area: civil},
				{name: 'Juzgado de Letras y Gar.de Pichilemu', area: civil},
				{name: 'Juzgado de Letras y Gar.de Litueche', area: civil},
				{name: 'Juzgado de Letras y Gar.de Peralillo', area: civil},
				{name: '1º Juzgado de Letras de Talca', area: civil},
				{name: '2º Juzgado de Letras de Talca', area: civil},
				{name: '3º Juzgado de Letras de Talca', area: civil},
				{name: '4º Juzgado de Letras de Talca', area: civil},
				{name: 'Juzgado de Letras de Constitución', area: civil},
				{name: 'Juzgado De Letras Y Gar. de Curepto', area: civil},
				{name: '1º Juzgado de Letras de Curico', area: civil},
				{name: '2º Juzgado de Letras de Curico', area: civil},
				{name: '2º Juzgado de Letras de Curico Ex 3º', area: civil},
				{name: 'Juzgado De Letras Y Gar. de Licanten', area: civil},
				{name: 'Juzgado de Letras de Molina', area: civil},
				{name: '1º Juzgado de Letras de Linares', area: civil},
				{name: '2º Juzgado de Letras de Linares', area: civil},
				{name: 'Juzgado de Letras de San Javier', area: civil},
				{name: 'Juzgado de Letras de Cauquenes', area: civil},
				{name: 'Juzgado de Letras y Gar. de Chanco', area: civil},
				{name: 'Juzgado de Letras de Parral', area: civil},
				{name: '1º Juzgado Civil de Chillan', area: civil},
				{name: '2º Juzgado Civil de Chillan', area: civil},
				{name: '1º Juzgado de Letras de San Carlos', area: civil},
				{name: 'Juzgado de Letras de Yungay', area: civil},
				{name: 'Juzgado de Letras y Gar. de Bulnes', area: civil},
				{name: 'Juzgado de Letras y Gar.de Coelemu', area: civil},
				{name: 'Juzgado de Letras y Gar.de Quirihue', area: civil},
				{name: '1º Juzgado de Letras de Los Angeles', area: civil},
				{name: '2º Juzgado de Letras de Los Angeles', area: civil},
				{name: '2° Juzgado de Letras de Los Angeles ex 3°', area: civil},
				{name: 'Juzgado de Letras y Gar. de Mulchen', area: civil},
				{name: 'Juzgado de Letras y Gar.de Nacimiento', area: civil},
				{name: 'Juzgado de Letras y Gar.de Laja', area: civil},
				{name: 'Juzgado de Letras y Gar.de Yumbel', area: civil},
				{name: '1º Juzgado Civil de Concepción', area: civil},
				{name: '2º Juzgado Civil de Concepción', area: civil},
				{name: '3º Juzgado Civil de Concepción', area: civil},
				{name: '1º Juzgado Civil de Talcahuano', area: civil},
				{name: '2º Juzgado Civil de Talcahuano', area: civil},
				{name: 'Juzgado de Letras de Tome', area: civil},
				{name: 'Juzgado de Letras y Gar.de Florida', area: civil},
				{name: 'Juzgado de Letras y Gar.de Santa Juana', area: civil},
				{name: 'Juzgado de Letras y Gar. de Lota', area: civil},
				{name: '1º Juzgado de Letras de Coronel', area: civil},
				{name: '2º Juzgado de Letras de Coronel', area: civil},
				{name: 'Juzgado de Letras y Gar.de Lebu', area: civil},
				{name: 'Juzgado de Letras de Arauco', area: civil},
				{name: 'Juzgado de Letras y Gar.de Curanilahue', area: civil},
				{name: 'Juzgado de Letras de Cañete', area: civil},
				{name: 'Juzgado de Letras y Gar. Santa Barbara', area: civil},
				{name: 'Juzgado de Letras y Gar.de Cabrero', area: civil},
				{name: '1º Juzgado Civil de Temuco', area: civil},
				{name: '2º Juzgado Civil de Temuco', area: civil},
				{name: 'Juzgado de Letras de Angol', area: civil},
				{name: 'Juzgado de Letras y Gar.de Collipulli', area: civil},
				{name: 'Juzgado de Letras y Gar.de Traiguen', area: civil},
				{name: 'Juzgado de Letras de Victoria', area: civil},
				{name: 'Juzgado de Letras y Gar.de Curacautin', area: civil},
				{name: 'Juzgado de Letras Loncoche', area: civil},
				{name: 'Juzgado de Letras de Pitrufquen', area: civil},
				{name: 'Juzgado de Letras de Villarrica', area: civil},
				{name: 'Juzgado de Letras de Nueva Imperial', area: civil},
				{name: 'Juzgado de Letras y Gar.de Pucon', area: civil},
				{name: 'Juzgado de Letras de Lautaro', area: civil},
				{name: 'Juzgado de Letras y Gar.de Carahue', area: civil},
				{name: '3º Juzgado Civil de Temuco', area: civil},
				{name: 'Juzgado de Letras y Gar.de Tolten', area: civil},
				{name: 'Juzgado de Letras y Gar.de Puren', area: civil},
				{name: '1º Juzgado Civil de Valdivia', area: civil},
				{name: '2º Juzgado Civil de Valdivia', area: civil},
				{name: 'Juzgado de Letras de Mariquina', area: civil},
				{name: 'Juzgado de Letras y Gar.de Paillaco', area: civil},
				{name: 'Juzgado de Letras Los Lagos', area: civil},
				{name: 'Juzgado de Letras y Gar. de Panguipulli', area: civil},
				{name: 'Juzgado de Letras y Gar.de la Union', area: civil},
				{name: 'Juzgado de Letras y Gar.de Rio Bueno', area: civil},
				{name: '1º Juzgado de Letras de Osorno', area: civil},
				{name: '2º Juzgado de Letras de Osorno', area: civil},
				{name: 'Juzgado de Letras de Rio Negro', area: civil},
				{name: '1º Juzgado Civil de Puerto Montt', area: civil},
				{name: 'Juzgado de Letras de Puerto Varas', area: civil},
				{name: 'Juzgado de Letras y Gar.de Calbuco', area: civil},
				{name: 'Juzgado de Letras y Gar. de Maullin', area: civil},
				{name: 'Juzgado de Letras de Castro', area: civil},
				{name: 'Juzgado de Letras de Ancud', area: civil},
				{name: 'Juzgado de Letras y Garantia de Achao', area: civil},
				{name: 'Juzgado de Letras y Gar. de Chaiten', area: civil},
				{name: 'Juzgado de Letras y Gar. de Los Muermos', area: civil},
				{name: 'Juzgado de Letras y Gar. de Quellon', area: civil},
				{name: '2º Juzgado Civil de Puerto Montt', area: civil},
				{name: 'Juzgado de Letras y Gar. de Hualaihue', area: civil},
				{name: '1º Juzgado de Letras de Coyhaique', area: civil},
				{name: '1º Juzgado de Letras de Coyhaique Ex 2º', area: civil},
				{name: 'Juzgado de Letras y Gar.de pto.Aysen', area: civil},
				{name: 'Juzgado de Letras y Gar.de Chile Chico', area: civil},
				{name: 'Juzgado de Letras y Gar.de Cochrane', area: civil},
				{name: 'Juzgado de Letras y Gar.de Puerto Cisnes', area: civil},
				{name: '1º Juzgado de Letras de Punta Arenas', area: civil},
				{name: '2º Juzgado de Letras de Punta Arenas', area: civil},
				{name: '3º Juzgado de Letras de Punta Arenas', area: civil},
				{name: 'Juzgado de Letras y Gar. de Puerto Natales', area: civil},
				{name: 'Juzgado de Letras y Gar.de Porvenir', area: civil},
				{name: 'Juzgado de Letras de Colina', area: civil},
				{name: '1º Juzgado Civil de Puente Alto', area: civil},	
				{name: '1° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '2° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '3° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '4° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '5° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '6° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '7° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '8° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '9° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '10° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '11° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '12° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '13° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '14° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '15° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '16° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '17° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '18° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '19° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '20° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '21° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '22° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '23° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '24° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '25° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '26° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '27° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '28° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '29° JUZGADO CORTE DE PRUEBA', area: civil},
				{name: '30° JUZGADO CORTE DE PRUEBA', area: civil},
		
		     ########################## Fin tribunales civiles del pais ############################

		     	# Tribunales de cobranza del país

		     {name: 'Jdo. de Letras y Garantía de Pozo Almonte', area: cobranza},
		     {name: 'Juzgado de Letras de Tocopilla', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Maria Elena', area: cobranza},
		     {name: 'Jdo. de Letras y Garantía de Taltal', area: cobranza},
		     {name: 'Jdo. de Letras y Garantía de Chañaral', area: cobranza},
		     {name: 'Juzgado de Letras de Diego de Almagro', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Freirina', area: cobranza},
		     {name: '1º Juzgado de Letras de Vallenar', area: cobranza},
		     {name: '2º Juzgado de Letras de Vallenar', area: cobranza},
		     {name: 'Juzgado de Letras de Vicuña', area: cobranza},		

		     {name: 'Juzgado de Letras y Garantía de Andacollo', area: cobranza},
		     {name: '1º Juzgado de Letras de Ovalle', area: cobranza},
		     {name: '2º Juzgado de Letras de Ovalle', area: cobranza},
		     {name: '3º Juzgado de Letras de Ovalle', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Combarbalá', area: cobranza},
		     {name: 'Juzgado de Letras de Illapel', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de los Vilos', area: cobranza},
		     {name: '1º Juzgado de Letras de Quilpué', area: cobranza},
		     {name: '2º Juzgado de Letras de Quilpué', area: cobranza},
		     {name: 'Jdo. de Letras de Villa Alemana', area: cobranza},

		     {name: 'Juzgado de Letras de CasaBlanca', area: cobranza},
		     {name: 'Jdo. de Letras de La Ligua', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Petorca', area: cobranza},
		     {name: '1º Juzgado de Letras de los Andes', area: cobranza},
		     {name: '2º Juzgado de Letras de los Andes', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Putaendo', area: cobranza},
		     {name: '1º Juzgado de Letras de Quillota', area: cobranza},
		     {name: '2º Juzgado de Letras de Quillota', area: cobranza},
		     {name: 'Jdo. de Letras de La Calera', area: cobranza},
		     {name: 'Juzgado de Letras de Limache', area: cobranza},

		     {name: '1º Juzgado de Letras de San Antonio', area: cobranza},
		     {name: '2º Juzgado de Letras de San Antonio', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Isla de Pascua', area: cobranza},
		     {name: 'Jdo. de Letras de Rengo', area: cobranza},
		     {name: 'Jdo. de Letras de San Vicente', area: cobranza},
		     {name: 'Jdo. de Letras y Garantía de Peumo', area: cobranza},
		     {name: '1°Jdo. de Letras de San Fernando', area: cobranza},
		     {name: '2°Jdo. de Letras de San Fernando', area: cobranza},
		     {name: 'Jdo. de Letras de Santa Cruz', area: cobranza},
		     {name: 'Jdo. de Letras y Garantía de Pichilemu', area: cobranza},

		     {name: 'Jdo. de Letras de Constitución<', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Curepto', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Licanten', area: cobranza},
		     {name: 'Juzgado de Letras de Molina', area: cobranza},
		     {name: '1º Juzgado de Letras de Linares', area: cobranza},
		     {name: '2º Juzgado de Letras de Linares', area: cobranza},
		     {name: 'Juzgado de Letras de San Javier', area: cobranza},
		     {name: 'Juzgado de Letras de Cauquenes', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Chanco', area: cobranza},
		     {name: 'Juzgado de Letras de Parral', area: cobranza},

		     {name: '1º Juzgado de Letras de San Carlos', area: cobranza},
		     {name: 'Juzgado de Letras de Yungay', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Bulnes', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Coelemu', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Quirihue', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Mulchen', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Nacimiento', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Laja', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Yumbel', area: cobranza},
		     {name: 'Juzgado de Letras de Tome', area: cobranza},

		     {name: 'Juzgado de Letras y Garantía de Florida', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Santa Juana', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Lota', area: cobranza},
		     {name: '1° Juzgado de Letras de Coronel', area: cobranza},
		     {name: '2° Juzgado de Letras de Coronel', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Lebu', area: cobranza},
		     {name: 'Juzgado de Letras de Arauco', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Curanilahue', area: cobranza},
		     {name: 'Juzgado de Letras de Cañete	', area: cobranza},
		     {name: '1°Jdo. de Letras de Angol', area: cobranza},

		     {name: 'Juzgado de Letras y Garantía de Collipulli', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Traiguen', area: cobranza},
		     {name: 'Juzgado de Letras de Victoria', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Curacautín', area: cobranza},
		     {name: 'Juzgado de Letras de Loncoche', area: cobranza},
		     {name: 'Juzgado de Letras de Pitrufquen', area: cobranza},
		     {name: 'Juzgado de Letras de Villarrica', area: cobranza},
		     {name: 'Juzgado de Letras de Nueva Imperial', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Pucón', area: cobranza},
		     {name: 'Juzgado de Letras de Lautaro', area: cobranza},

		     {name: 'Juzgado de Letras y Garantía de Carahue', area: cobranza},
		     {name: 'Jdo. de Letras de Mariquina', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Paillaco', area: cobranza},
		     {name: 'Juzgado de Letras de Los Lagos', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Panguipulli', area: cobranza},
		     {name: 'Jdo. de Letras y Garantía de La Unión', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Rio Bueno', area: cobranza},
		     {name: '1º Juzgado de Letras de Puerto Varas', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Calbuco', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Maullin', area: cobranza},

		     {name: 'Juzgado de Letras de Ancud', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Achao', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Chaiten', area: cobranza},
		     {name: 'Jdo. de Letras de Letras y Garantia de Aysén', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Chile Chico<', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Cochrane', area: cobranza},
		     {name: 'Jdo. de Letras y Garantía de Puerto Natales', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Porvenir', area: cobranza},
		     {name: '1° Juzgado de Letras de Talagante', area: cobranza},
		     {name: '2° Juzgado de Letras de Talagante', area: cobranza},

		     {name: '1° Juzgado de Letras de Melipilla', area: cobranza},
		     {name: '1° Juzgado de Letras de Buin', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Santa Barbara', area: cobranza},
		     {name: 'Juzgado de Letras y Garantia de Caldera', area: cobranza},
		     {name: 'Jdo. de Letras de Colina', area: cobranza},
		     {name: 'Juzgado de Letras de Peñaflor', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Los Muermo', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Quintero', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Tolten', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Puren', area: cobranza},

		     {name: 'Juzgado de Letras y Garantía de Puerto', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Hualaihue', area: cobranza},
		     {name: 'Jdo. de Letras y Garantía de Litueche', area: cobranza},
		     {name: 'Jdo. de Letras y Garantía de Peralillo', area: cobranza},
		     {name: 'Juzgado de Letras y Garantía de Cabrero', area: cobranza},
		     {name: 'Jdo. Cob. Laboral y Previsional de Santiago', area: cobranza},
		     {name: 'Jdo. Cob. Laboral y Previsional de San Miguel', area: cobranza},
		     {name: 'Jdo. Cob. Laboral y Previsional de Valparaíso', area: cobranza},
		     {name: 'Jdo. Cob. Laboral y Previsional de Concepción', area: cobranza},
		     {name: 'Jdo. de Letras del Trabajo de Arica', area: cobranza},

		     {name: 'Jdo. de Letras del Trabajo de Iquique', area: cobranza},
		     {name: 'Jdo. de Letras del Trabajo de Antofagasta', area: cobranza},
		     {name: 'Jdo. de Letras del Trabajo de Copiapó', area: cobranza},
		     {name: 'Jdo. de Letras del Trabajo de La Serena', area: cobranza},
		     {name: 'Jdo. de Letras del Trabajo de Rancagua', area: cobranza},
		     {name: 'Jdo. de Letras del Trabajo de Curicó', area: cobranza},
		     {name: 'Jdo. de Letras del Trabajo de Talca', area: cobranza},
		     {name: 'Juzgado de Letras del Trabajo de Chillán', area: cobranza},
		     {name: 'Jdo. de Letras del Trabajo de Temuco', area: cobranza},
		     {name: 'Jdo. de Letras del Trabajo de Valdivia', area: cobranza},

		     {name: 'Jdo. de Letras del Trabajo de Puerto Montt', area: cobranza},
		     {name: 'Jdo. de Letras del Trabajo Punta Arenas', area: cobranza},
		     {name: 'Jdo. de Letras del Trabajo de San Bernardo', area: cobranza},
		     {name: 'Jdo. de Letras del Trabajo de Calama', area: cobranza},
		     {name: 'Jdo. de Letras del Trabajo de San Felipe', area: cobranza},
		     {name: 'Jdo. de Letras del Trabajo de Los Ángeles', area: cobranza},
		     {name: 'Jdo. de Letras del Trabajo de Osorno', area: cobranza},
		     {name: 'Jdo. de Letras del Trabajo de Castro', area: cobranza},
		     {name: 'Jdo. de Letras del Trabajo de Coyhaique', area: cobranza},
		     {name: 'Jdo. de Letras del Trabajo de Puente Alto', area: cobranza},


		     ########################## Fin Tribunales Cobranza del pais ###########################

		     	# Tribunales Penales del país

		     #C.A. DE ARICA.
			 {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL DE ARICA.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE ARICA.', area: penal},

		     #C.A. DE IQUIQUE.
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE POZO ALMONTE.', area: penal},
		     {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL DE IQUIQUE.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE IQUIQUE.', area: penal},

		     #C.A. DE ANTOFAGASTA.
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE MARÍA ELENA.', area: penal},
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE TALTAL.', area: penal},
		     {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL DE CALAMA.', area: penal},
		     {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL DE ANTOFAGASTA.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE TOCOPILLA.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE CALAMA.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE ANTOFAGASTA.', area: penal},

		     #C.A. DE COPIAPÓ.
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE CHAÑARAL.', area: penal},
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE FREIRINA.', area: penal},
		     {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL DE COPIAPO.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE DIEGO DE ALMAGRO.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE COPIAPO.', area: penal},

		     #C.A. DE LA SERENA.
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE ANDACOLLO.', area: penal},
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE COMBARBALA.', area: penal},
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE LOS VILOS.', area: penal},
		     {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL DE LA SERENA.', area: penal},
		     {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL DE OVALLE.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE LA SERENA.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE COQUIMBO.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE VICUÑA.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE ILLAPEL.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE OVALLE.	', area: penal},

		     #C.A. DE VALPARAÍSO.
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE PETORCA.', area: penal},
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE PUTAENDO.', area: penal},
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE ISLA DE PASCUA.', area: penal},
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE QUINTERO.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE VALPARAÍSO.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE VIÑA DEL MAR.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE QUILPUÉ.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE SAN ANTONIO.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE CASABLANCA', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE LA LIGUA.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE SAN FELIPE.', area: penal},
		     {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL DE QUILLOTA.', area: penal},
		     {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL DE VALPARAÍSO.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE LIMACHE.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE LA CALERA.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE QUILLOTA.', area: penal},
		     {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL DE LOS ANDES.', area: penal},
		     {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL DE SAN FELIPE.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE LOS ANDES.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE VILLA ALEMANA.', area: penal},
		     {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL VIÑA DEL MAR.', area: penal},

		     #C.A. DE RANCAGUA.
		     {name: '1º JUZGADO DE LETRAS Y GARANTÍA DE PEUMO.', area: penal},
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE PICHILEMU.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE SAN FERNANDO.', area: penal},
		     {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL DE SANTA CRUZ.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE SANTA CRUZ.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE RENGO.', area: penal},
		     {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL SAN FERNANDO.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE GRANEROS.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE RANCAGUA.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE SAN VICENTE DE TAGUA-TAGUA.', area: penal},
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE PERALILLO.', area: penal},
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE LITUECHE.', area: penal},
		     {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL DE RANCAGUA.', area: penal},

		     #C.A. DE TALCA.
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE CUREPTO.', area: penal},
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE LICANTEN.', area: penal},
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE CHANCO.', area: penal},
		     {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL DE CURICO.', area: penal},
		     {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL DE LINARES.', area: penal},
		     {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL DE CAUQUENES.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE CURICO.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE MOLINA.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE CONSTITUCIÓN.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE TALCA.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE SAN JAVIER.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE CAUQUENES.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE LINARES.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE PARRAL.', area: penal},
		     {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL DE TALCA.', area: penal},

		     #C.A. DE CHILLÁN.
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE BULNES.', area: penal},
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE COELEMU.', area: penal},
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE QUIRIHUE.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE CHILLÁN.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE YUNGAY.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE SAN CARLOS.', area: penal},
		     {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL DE CHILLÁN.', area: penal},

		     #C.A. DE CONCEPCIÓN.
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE MULCHEN.', area: penal},
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE NACIMIENTO.', area: penal},
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE LAJA.', area: penal},
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE YUMBEL.', area: penal},
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE FLORIDA.', area: penal},
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE SANTA JUANA.', area: penal},
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE LOTA.', area: penal},
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE CURANILAHUE.', area: penal},
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE SANTA BARBARA.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE SAN PEDRO DE LA PAZ.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE CAÑETE.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE ARAUCO.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE CORONEL.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE TOMÉ.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE TALCAHUANO.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE CHIGUAYANTE.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE CONCEPCIÓN.', area: penal},
		     {name: 'JUZGADO DE GARANTÍA DE LOS ANGELES.', area: penal},
		     {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL DE CONCEPCIÓN.', area: penal},
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE LEBU.', area: penal},
		     {name: 'JUZGADO DE LETRAS Y GARANTÍA DE CABRERO.', area: penal},
		     {name: 'TRIBUNAL ORAL EN LO PENAL DE LOS ANGELES.', area: penal},
		     {name: 'TRIBUNAL ORAL EN LO PENAL DE CAÑETE.', area: penal},

		     #C.A. DE TEMUCO.
			 {name: 'JUZGADO DE LETRAS Y GARANTÍA DE COLLIPULLI.', area: penal},
			 {name: 'JUZGADO DE LETRAS Y GARANTÍA DE TRAIGUEN.', area: penal},
			 {name: 'JUZGADO DE LETRAS Y GARANTÍA DE CURACAUTIN.', area: penal},
			 {name: 'JUZGADO DE LETRAS Y GARANTÍA DE PUCON.', area: penal},
			 {name: 'JUZGADO DE LETRAS Y GARANTÍA DE CARAHUE.', area: penal},
			 {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL DE TEMUCO.', area: penal},
			 {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL DE ANGOL.', area: penal},
			 {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL DE VILLARRICA.', area: penal},
			 {name: 'JUZGADO DE GARANTÍA DE TEMUCO.', area: penal},
			 {name: 'JUZGADO DE GARANTÍA DE PITRUFQUEN.', area: penal},
			 {name: 'JUZGADO DE GARANTÍA DE VILLARRICA.', area: penal},
			 {name: 'JUZGADO DE GARANTÍA DE ANGOL.', area: penal},
			 {name: 'JUZGADO DE GARANTÍA DE VICTORIA.', area: penal},
			 {name: 'JUZGADO DE GARANTÍA DE NUEVA IMPERIAL.', area: penal},
			 {name: 'JUZGADO DE GARANTÍA DE LAUTARO.', area: penal},
			 {name: 'JUZGADO DE GARANTÍA DE LONCOCHE', area: penal},
			 {name: 'JUZGADO DE LETRAS Y GARANTÍA DE TOLTEN.', area: penal},
			 {name: 'JUZGADO DE LETRAS Y GARANTÍA DE PUREN.', area: penal},	

			 # C.A. DE VALDIVIA.	     
			 {name: 'JUZGADO DE LETRAS Y GARANTÍA DE PAILLACO.', area: penal},
			 {name: 'JUZGADO DE LETRAS Y GARANTÍA DE PANGUIPULLI.', area: penal},
			 {name: 'JUZGADO DE LETRAS Y GARANTÍA DE LA UNIÓN.', area: penal},
			 {name: 'JUZGADO DE LETRAS Y GARANTÍA DE RÍO BUENO.', area: penal},
			 {name: 'JUZGADO DE GARANTÍA DE VALDIVIA.', area: penal},
			 {name: 'JUZGADO DE GARANTÍA DE MARIQUINA.', area: penal},
			 {name: 'JUZGADO DE GARANTÍA DE LOS LAGOS.', area: penal},
			 {name: 'JUZGADO DE GARANTÍA DE RÍO NEGRO.', area: penal},
			 {name: 'JUZGADO DE GARANTÍA DE OSORNO.', area: penal},
			 {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL DE VALDIVIA.', area: penal},
			 {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL DE OSORNO', area: penal},
			 
			 #C.A. DE PUERTO MONTT.
			 {name: 'JUZGADO DE LETRAS Y GARANTÍA DE CALBUCO.', area: penal},
			 {name: 'JUZGADO DE LETRAS Y GARANTÍA DE MAULLIN.', area: penal},
			 {name: 'JUZGADO DE LETRAS Y GARANTÍA DE ACHAO.', area: penal},
			 {name: 'JUZGADO DE LETRAS Y GARANTÍA DE CHAITEN.', area: penal},
			 {name: 'JUZGADO DE LETRAS Y GARANTÍA DE LOS MUERMOS.', area: penal},
			 {name: 'JUZGADO DE LETRAS Y GARANTÍA DE QUELLON.', area: penal},
			 {name: 'JUZGADO DE GARANTÍA DE CASTRO.', area: penal},		     
			 {name: 'JUZGADO DE GARANTÍA DE PUERTO MONTT.', area: penal},
			 {name: 'JUZGADO DE GARANTÍA DE PUERTO VARAS.', area: penal},
			 {name: 'JUZGADO DE GARANTÍA DE ANCUD.', area: penal},
			 {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL PUERTO MONTT.', area: penal},
			 {name: 'TRIBUNAL ORAL EN LO PENAL DE CASTRO', area: penal},
			 {name: 'JUGADO DE LETRAS Y GARANTÍA DE HUALAIHUE', area: penal},

			 #C.A. DE COYHAIQUE.
			 {name: 'JUZGADO DE LETRAS Y GARANTÍA DE PUERTO AYSEN.', area: penal},
			 {name: 'JUZGADO DE LETRAS Y GARANTÍA DE CHILE CHICO.', area: penal},
			 {name: 'JUZGADO DE LETRAS Y GARANTÍA DE COCHRANE.', area: penal},
			 {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL DE COYHAIQUE.', area: penal},
			 {name: 'JUZGADO DE GARANTÍA DE COYHAIQUE.', area: penal},
			 {name: 'JUZGADO DE LETRAS Y GARANTÍA DE CISNES.', area: penal},

			 #C.A. DE PUNTA ARENAS.
			 {name: 'JUZGADO DE LETRAS Y GARANTÍA DE PUERTO NATALES.', area: penal},			 
			 {name: 'JUZGADO DE LETRAS Y GARANTÍA DE PORVENIR.', area: penal},
			 {name: 'TRIBUNAL DE JUICIO ORAL EN LO PENAL PUNTA ARENAS.', area: penal},
			 {name: 'JUZGADO DE GARANTÍA DE PUNTA ARENAS.', area: penal},



		     ########################## Fin Tribunales Penales del país #############################
 
 				# Tribunales laborales de todo el pais

 				#C.A. de Arica
				{name: 'Juzgado de Letras del Trabajo de Arica', area: laboral},
				{name: 'Juzgado de Letras del Trabajo de Iquique', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Pozo Almonte', area: laboral},
				{name: 'Juzgado de Letras de Tocopilla', area: laboral},
				{name: 'Juzgado de Letras del Trabajo de Antofagasta', area: laboral},
				{name: 'Juzgado de Letras del Trabajo de Calama', area: laboral},
				{name: 'Juzgado de Letras y Garantía de María Elena', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Taltal', area: laboral},

				# C.A. de Copiapo
				{name: 'Juzgado de Letras del Trabajo de Copiapó', area: laboral},
				{name: 'Juzgado de Letras y Garantia de Chañaral', area: laboral},
				{name: 'Juzgado de Letras de Diego de Almagro', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Freirina', area: laboral},
				{name: '1° Juzgado de Letras de Vallenar', area: laboral},
				{name: '2° Juzgado de Letras de Vallenar', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Caldera', area: laboral},

				#C.A. de La Serena
				{name: 'Juzgado de Letras del Trabajo de La Serena', area: laboral},
				{name: 'Juzgado de Letras de Vicuña', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Andacollo', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Andacollo', area: laboral},
				{name: '1º Juzgado de Letras de Ovalle', area: laboral},
				{name: '2º Juzgado de Letras de Ovalle', area: laboral},
				{name: '3º Juzgado de Letras de Ovalle', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Combarbalá', area: laboral},
				{name: 'Juzgado de Letras de Illapel', area: laboral},
				{name: 'Juzgado de Letras y Garantía de los Vilos', area: laboral},

				#C.A. de Valparaiso
				{name: '1° Juzgado de Letras de San Antonio', area: laboral},
				{name: '2° Juzgado de Letras de San Antonio', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Isla de Pascua', area: laboral},
				{name: 'Juzgado de Letras del Trabajo de Valparaíso', area: laboral},
				{name: 'Juzgado de Letras del Trabajo de San Felipe', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Quintero', area: laboral},
				{name: '1º Juzgado de Letras de Quilpue', area: laboral},
				{name: '2º Juzgado de Letras de Quilpue', area: laboral},
				{name: 'Juzgado de Letras de Villa Alemana', area: laboral},
				{name: 'Juzgado de Letras de Casa Blanca', area: laboral},
				{name: 'Juzgado de Letras de La Ligua', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Petorca', area: laboral},
				{name: '1º Juzgado de Letras de Los Andes', area: laboral},
				{name: '2º Juzgado de Letras de Los Andes', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Putaendo', area: laboral},
				{name: '1º Juzgado de Letras de Quillota', area: laboral},
				{name: '2º Juzgado de Letras de Quillota', area: laboral},
				{name: 'Juzgado de Letras de La Calera', area: laboral},
				{name: 'Juzgado de Letras de Limache', area: laboral},

				#C.A. de Rancagua
				{name: '1º Juzgado de Letras de Rengo', area: laboral},
				{name: 'Juzgado de Letras de San Vicente', area: laboral},
				{name: '1º Juzgado de Letras y Garantia de Peumo', area: laboral},
				{name: '1º Juzgado de Letras de San Fernando', area: laboral},
				{name: '2º Juzgado de Letras de San Fernando', area: laboral},
				{name: 'Juzgado de Letras y Garantia de Litueche', area: laboral},
				{name: 'Juzgado de Letras y Garantia de Peralillo', area: laboral},
				{name: '1º Juzgado de Letras de Santa Cruz', area: laboral},
				{name: 'Juzgado de Letras y Garantia de Pichilemu', area: laboral},
				{name: 'Juzgado de Letras del Trabajo de Rancagua', area: laboral},

				#C.A. de Talca
				{name: 'Juzgado de Letras de Constitución', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Curepto', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Licantén', area: laboral},
				{name: 'Juzgado de Letras de Molina', area: laboral},
				{name: 'Juzgado de Letras del Trabajo de Curicó', area: laboral},
				{name: 'Juzgado de Letras del Trabajo de Talca', area: laboral},
				{name: '1° Juzgado de Letras de Linares', area: laboral},
				{name: '2° Juzgado de Letras de Linares', area: laboral},
				{name: 'Juzgado de Letras de San Javier', area: laboral},
				{name: 'Juzgado de Letras de Cauquenes', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Chanco', area: laboral},
				{name: 'Juzgado de Letras de Parral', area: laboral},

				#C.A. de Chillan
				{name: 'Juzgado de Letras del Trabajo de Chillán', area: laboral},
				{name: '1° Juzgado de Letras de San Carlos', area: laboral},
				{name: 'Juzgado de Letras de Yungay', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Bulnes', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Coelemu', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Quirihue', area: laboral},

				#C.A. de Concepción
				{name: 'Juzgado de Letras y Garantía de Cabrero', area: laboral},
				{name: 'Juzgado de Letras del Trabajo de Concepción', area: laboral},
				{name: 'Juzgado de Letras del Trabajo de Los Angeles', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Mulchén', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Nacimiento', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Laja', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Yumbel', area: laboral},
				{name: 'Juzgado de Letras de Tomé', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Florida', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Santa Juana', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Lota', area: laboral},
				{name: '1er Juzgado de Letras de Coronel', area: laboral},
				{name: '2er Juzgado de Letras de Coronel', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Lebu', area: laboral},
				{name: 'Juzgado de Letras de Arauco', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Curanilahue', area: laboral},
				{name: 'Juzgado de Letras de Cañete', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Santa Bárbara', area: laboral},				

				#C.A. de Temuco
				{name: 'Juzgado de Letras del Trabajo de Temuco', area: laboral},
				{name: '1º Juzgado de Letras de Angol', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Collipulli', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Traiguen', area: laboral},
				{name: 'Juzgado de Letras de Victoria', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Curacautín', area: laboral},
				{name: 'Juzgado de Letras de Loncoche', area: laboral},
				{name: 'Juzgado de Letras de Pitrufquén', area: laboral},
				{name: 'Juzgado de Letras de Villarrica', area: laboral},
				{name: 'Juzgado de Letras de Nueva Imperial', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Pucón', area: laboral},
				{name: 'Juzgado de Letras de Lautaro', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Carahue', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Toltén', area: laboral},				
				{name: 'Juzgado de Letras y Garantía de Purén', area: laboral},				

				#C.A. de Valdivia
				{name: 'Juzgado de Letras del Trabajo de Valdivia', area: laboral},
				{name: 'Juzgado de Letras del Trabajo de Osorno', area: laboral},
				{name: 'Juzgado de Letras de Mariquina', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Paillaco', area: laboral},
				{name: 'Juzgado de Letras de Los Lagos', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Panguipulli', area: laboral},
				{name: 'Juzgado de Letras y Garantía de La Unión', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Río Bueno', area: laboral},

				#C.A. de Puerto Montt
				{name: 'Juzgado de Letras y Garantía de Hualaihue', area: laboral},
				{name: 'Juzgado de Letras del Trabajo de Puerto Montt', area: laboral},
				{name: 'Juzgado de Letras del Trabajo de Castro', area: laboral},
				{name: '1º Juzgado de Letras de Puerto Varas', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Calbuco', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Maullín', area: laboral},
				{name: 'Juzgado de Letras de Ancud', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Achao', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Chaitén', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Los Muermos', area: laboral},

				#C.A. de Coyhaique
				{name: 'Juzgado de Letras del Trabajo de Coyhaique', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Aysén', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Chile Chico', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Cochrane', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Puerto Cisnes', area: laboral},

				#C.A. de Punta Arenas
				{name: 'Juzgado de Letras del Trabajo de Punta Arenas', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Puerto Natales', area: laboral},
				{name: 'Juzgado de Letras y Garantía de Porvenir', area: laboral},

				# Fin tribunales laborales del pais
#-##############################################################################################-#

				# TRBUNALES CORTE DE APELACIONES DEL PAÍS

			{name: 'C.A Antofagasta', area: supr_apel},
			{name: 'C.A Arica', area: supr_apel},
			{name: 'C.A Chillan', area: supr_apel},
			{name: 'C.A Concepción', area: supr_apel},
			{name: 'C.A Copiapó', area: supr_apel},
			{name: 'C.A Coyhaique', area: supr_apel},
			{name: 'C.A Iquique', area: supr_apel},
			{name: 'C.A La Serena', area: supr_apel},
			{name: 'C.A De Prueba', area: supr_apel},
			{name: 'C.A Puerto Montt', area: supr_apel},
			{name: 'C.A Punta Arenas', area: supr_apel},
			{name: 'C.A Rancagua', area: supr_apel},
			{name: 'C.A Talca', area: supr_apel},
			{name: 'C.A Temuco', area: supr_apel},
			{name: 'C.A Valdivia', area: supr_apel},
			{name: 'C.A Valparaíso', area: supr_apel},


#-####################Fin Corte de apelaciones####################################################-#

				{name: '1º Juzgado Civil de San Miguel', area: civil, region: san_miguel},
				{name: '2º Juzgado Civil de San Miguel', area: civil, region: san_miguel},
				{name: '3º Juzgado Civil de San Miguel', area: civil, region: san_miguel},
				{name: '4º Juzgado Civil de San Miguel', area: civil, region: san_miguel},
				{name: '1º Juzgado De Letras De Talagante', area: civil, region: san_miguel},
				{name: '2º Juzgado De Letras De Talagante', area: civil, region: san_miguel},
				{name: '1º Juzgado de Letras de Melipilla', area: civil, region: san_miguel},
				{name: '1º Juzgado de Letras de Buin', area: civil, region: san_miguel},
				{name: '2º Juzgado de Letras de Buin', area: civil, region: san_miguel},
				{name: 'Juzgado de Letras de Peñaflor', area: civil, region: san_miguel},
				{name: '1º Juzgado de Letras de San Bernardo', area: civil, region: san_miguel},
				{name: '2º Juzgado de Letras de San Bernardo', area: civil, region: san_miguel},
				{name: '1º Juzgado de Letras de San Bernardo Ex 3°', area: civil, region: san_miguel},
				{name: '2º Juzgado de Letras de San Bernardo Ex 3°', area: civil, region: san_miguel},
				{name: 'Juzgado de Letras del Trabajo de San Miguel', area: laboral, region: san_miguel},
				{name: 'Juzgado de Letras del Trabajo de San Bernardo', area: laboral, region: san_miguel},
				{name: 'Juzgado de Letras del Trabajo de Puente Alto', area: laboral, region: san_miguel},

				#Tribunales laborales faltantes san miguel
				{name: '1° Juzgado de Letras de Talagante', area: laboral, region: san_miguel},
				{name: '2° Juzgado de Letras de Talagante', area: laboral, region: san_miguel},
				{name: '1er Juzgado de Letras de Melipilla', area: laboral, region: san_miguel},
				{name: '1er Juzgado de Letras de Buin', area: laboral, region: san_miguel},
				{name: '2er Juzgado de Letras de Buin', area: laboral, region: san_miguel},
				{name: 'Juzgado de Letras de Peñaflor', area: laboral, region: san_miguel},
				# fin

				{name: 'Juzgado de Cobranza Laboral y Previsional San Miguel', area: cobranza, region: san_miguel},
				{name: '1º Juzgado de Familia San Miguel', area: familia, region: san_miguel},
				{name: '2º Juzgado de Familia San Miguel', area: familia, region: san_miguel},
				{name: 'Juzgado de Familia Buin', area: familia, region: san_miguel},
				{name: 'Juzgado de Familia Melipilla', area: familia, region: san_miguel},
				{name: 'Juzgado de Familia Peñaflor', area: familia, region: san_miguel},
				{name: 'Juzgado de Familia Puente Alto', area: familia, region: san_miguel},
				{name: 'Juzgado de Familia San Bernardo', area: familia, region: san_miguel},
				{name: 'Juzgado de Familia Talagante', area: familia, region: san_miguel},
				{name: '10º Juzgado de Garantía de Santiago', area: penal, region: san_miguel},
				{name: '11º Juzgado de Garantía de Santiago', area: penal, region: san_miguel},
				{name: '12º Juzgado de Garantía de Santiago', area: penal, region: san_miguel},
				{name: '15º Juzgado de Garantía de Santiago', area: penal, region: san_miguel},
				{name: 'Juzgado de Garantía de Puente Alto', area: penal, region: san_miguel},
				{name: 'Juzgado de Garantía de San Bernardo', area: penal, region: san_miguel},
				{name: 'Juzgado de Garantía de Melipilla', area: penal, region: san_miguel},
				{name: 'Juzgado de Garantía de Curacaví', area: penal, region: san_miguel},
				{name: 'Juzgado de Garantía de Talagante', area: penal, region: san_miguel},
				{name: '6º Tribunal de Juicio Oral en lo Penal de Santiago', area: penal, region: san_miguel},
				{name: 'Tribunal de Juicio Oral en lo Penal de Talagante', area: penal, region: san_miguel},
				{name: 'Tribunal de Juicio Oral en lo Penal de Puente Alto', area: penal, region: san_miguel},
				{name: 'Tribunal de Juicio Oral en lo Penal de San Bernardo', area: penal, region: san_miguel},
				{name: 'Tribunal de Juicio Oral en lo Penal de Melipilla', area: penal, region: san_miguel},
				{name: 'Sin Tribunal', area: general, region: santiago}]

